export const NEW_ITEM_IN_CART = 'NEW_ITEM_IN_CART'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const MADE_ORDER_SUCCESS = 'MADE_ORDER_SUCCESS'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'