export const LOAD_IMAGE = 'LOAD_IMAGE'
export const SAVE_TEMPLATE = 'SAVE_TEMPLATE'
export const EDIT_FIELD = 'EDIT_FIELD'
export const LOAD_TEMPLATE = 'LOAD_TEMPLATE'
export const ADD_FIELD = 'ADD_FIELD'
export const GET_FIELDS = 'GET_FIELDS'
export const ADD_ITEM = 'ADD_ITEM'