export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST'
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE'
export const LOAD_IMAGE_SUCCESS = 'LOAD_IMAGE_SUCCESS'
export const LOAD_TEMPLATE_SUCCESS = 'LOAD_TEMPLATE_SUCCESS'
